FROM nriet/tomcat:8.5.82-jdk8-openjdk-slim-buster

MAINTAINER Axiu <itzyx@vip.qq.com>

ENV TZ PRC

ENV RESTCLOUD_WAR_URL https://etl.restcloud.cn/download/RestCloud-ETL-V3.2.war

 # thredds
 RUN apt-get update && \
    apt-get install -y --no-install-recommends net-tools \
        libpthread-stubs0-dev libcurl4-openssl-dev zip unzip && \
    apt-get clean && \
	rm -rf /var/lib/apt/lists/* && \
	#RESTCLOUD
	curl -fSL "${RESTCLOUD_WAR_URL}" -o ROOT.war && \
	rm -rf /usr/local/tomcat/webapps/*  && \
	unzip ROOT.war -d ${CATALINA_HOME}/webapps/ROOT/ && \
	rm -f ROOT.war
	
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

#COPY application.properties /usr/local/tomcat/webapps/ROOT/WEB-INF/classes/

EXPOSE 8080 8443

# Start container
CMD ["catalina.sh", "run"]

HEALTHCHECK --interval=10s --timeout=3s \
	CMD curl --fail 'http://localhost:8080/restcloud/view/page/index.html' || exit 1

