FROM nriet/tomcat:8.5.82-jdk8-openjdk-slim-buster

MAINTAINER Axiu <itzyx@vip.qq.com>

ENV TZ PRC

ENV RESTCLOUD_VERSION 3.2

COPY war/RestCloud-ETL-V${RESTCLOUD_VERSION}.war /tmp/RestCloud.war
RUN ls -l /tmp
RUN apt-get update && \
    apt-get install -y --no-install-recommends unzip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
	rm -rf /usr/local/tomcat/webapps/*  && \
	mkdir -p /usr/local/tomcat/webapps/ROOT/ && \
	unzip /tmp/RestCloud.war -d /usr/local/tomcat/webapps/ROOT/ && \
	rm -rf /tmp/RestCloud.war

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

#COPY application.properties /usr/local/tomcat/webapps/ROOT/WEB-INF/classes/

EXPOSE 8080 8443

# Start container
CMD ["catalina.sh", "run"]

HEALTHCHECK --interval=10s --timeout=3s \
	CMD curl --fail 'http://localhost:8080/restcloud/view/page/index.html' || exit 1

