FROM nriet/tomcat:8.5.82-jdk8-openjdk-slim-buster

MAINTAINER Axiu <itzyx@vip.qq.com>

ENV TZ PRC

ENV RESTCLOUD_VERSION 3.2

RUN set -eux && \
	apt-get update && \
	apt-get install -y --no-install-recommends net-tools wget unzip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
	rm -rf /var/cache/apt 

RUN set -eux; \
	\
	wget -O ROOT.war "https://etl.restcloud.cn/download/RestCloud-ETL-V${RESTCLOUD_VERSION}.war" --no-check-certificate; \
	rm -rf /usr/local/tomcat/webapps/*; \
	unzip -oq ROOT.war -d /usr/local/tomcat/webapps/ROOT; \
	rm -rf ROOT.war 
	
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

EXPOSE 8080 8443

# Start container
CMD ["catalina.sh", "run"]

HEALTHCHECK --interval=10s --timeout=3s \
	CMD curl --fail 'http://localhost:8080/restcloud/view/page/index.html' || exit 1

