# docker-image.yml
name: Publish Docker image   # workflow名称，可以在Github项目主页的【Actions】中看到所有的workflow
env:
  APP_NAME: restcloud
  DOCKERHUB_REPO: nriet/restcloud
  APP_VERSION: 3.8
on:   # 配置触发workflow的事件
  push:
    branches:   # master分支有push时触发此workflow
      - 'master'
    tags:       # tag更新时触发此workflow
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}  # 配置dockerhub的认证，在Github项目主页 【Settings】 -> 【Secrets】 添加对应变量
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      # - 
        # name: Generate App Version
        # run: echo APP_VERSION=`git describe --tags --always` >> $GITHUB_ENV
      - name: 8.5jdk
        uses: docker/build-push-action@v2 # docker build  & push
        with:
          file: Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            ${{ env.DOCKERHUB_REPO }}:latest
            ${{ env.DOCKERHUB_REPO }}:${{ env.APP_VERSION }}
      # - name: 8.5jdk
      #   uses: docker/build-push-action@v2 # docker build  & push
      #   with:
      #     file: Dockerfile-python3
      #     platforms: |
      #       linux/amd64
      #       linux/arm64
      #     push: true
      #     tags: |
      #       ${{ env.DOCKERHUB_REPO }}:latest
      #       ${{ env.DOCKERHUB_REPO }}:${{ env.APP_VERSION }}-python3
      - name: slim-buster
        uses: docker/build-push-action@v2 # docker build  & push
        with:
          file: Dockerfile-slim-buster
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: ${{ env.DOCKERHUB_REPO }}:${{ env.APP_VERSION }}-slim-buster
      - name: slim-buster-python3
        uses: docker/build-push-action@v2 # docker build  & push
        with:
          file: Dockerfile-slim-buster-python3
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: ${{ env.DOCKERHUB_REPO }}:${{ env.APP_VERSION }}-slim-buster-python3
      # - name: restcloud:3.2-slim-buster-python3
      #   uses: docker/build-push-action@v2 # docker build  & push
      #   with:
      #     context: slim-buster-python3/.
      #     push: true
      #     tags: ${{ env.DOCKERHUB_REPO }}:${{ env.APP_VERSION }}-slim-buster-python3
          
      # - name: restcloud:2.5-slim-buster-python3-fj
      #   uses: docker/build-push-action@v2 # docker build  & push
      #   with:
      #     context: fj/.
      #     push: true
      #     tags: nriet/restcloud:2.5-slim-buster-python3-fj
          
      # - name: restcloud:3.2-slim-buster-python3-zj-climate
      #   uses: docker/build-push-action@v2 # docker build  & push
      #   with:
      #     context: zj-climate/.
      #     push: true
      #     tags: ${{ env.DOCKERHUB_REPO }}:${{ env.APP_VERSION }}-slim-buster-python3-zj-climate
          
      # - name: restcloud:2.5-slim-buster-zj-climate-miniconda
      #   uses: docker/build-push-action@v2 # docker build  & push
      #   with:
      #     context: zj-climate-miniconda/.
      #     push: true
      #     tags: nriet/restcloud:2.5-slim-buster-zj-climate-miniconda
          
      # - name: restcloud:1.6.1-slim-buster-python3-ah
      #   uses: docker/build-push-action@v2 # docker build  & push
      #   with:
      #     context: ah/.
      #     push: true
      #     tags: nriet/restcloud:1.6.1-slim-buster-python3-ah